version: '0.5.0-beta{build}'

image: Visual Studio 2017
configuration: Release

before_build:
- pwsh: appveyor-retry dotnet restore .\src\HttpRecorder.sln

build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'

nuget:
  project_feed: true

